In [1]:
import numpy as np

In [2]:
array_one = np.array([0,1,3,5,7,9])
array_one

array([0, 1, 3, 5, 7, 9])

In [3]:
num = [11, 22, 33, 44, 55, 66, 77]
array_two = np.array(num)
array_two

array([11, 22, 33, 44, 55, 66, 77])

In [4]:
array_of_zeros = np.zeros((2,3))
array_of_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
array_of_ones = np.ones((3,2))
array_of_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
array_of_ones = np.ones((3,2), dtype=np.int32)
array_of_ones

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [8]:
array_empty = np.empty((3,2))
array_empty

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
array_eye = np.eye(4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
array_of_evens = np.arange(2,24,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [13]:
array_of_floats = np.arange(1, 3, 0.3)
array_of_floats

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8])

In [14]:
array_2d = np.array([(3,4,6),(2,1,6)])
array_2d

array([[3, 4, 6],
       [2, 1, 6]])

In [15]:
array_2d.shape

(2, 3)

In [16]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
array_nd = np.arange(8).reshape(2,4)
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [19]:
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
_3d_array = np.arange(36).reshape(3,4,3)
print(_3d_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [23]:
p = np.array([9,8,7])
q = np.array([3,2,4])

In [24]:
p + q

array([12, 10, 11])

In [25]:
p-q

array([6, 6, 3])

In [26]:
p*q

array([27, 16, 28])

In [27]:
p/q

array([3.  , 4.  , 1.75])

In [28]:
p%q

array([0, 0, 3])

In [29]:
p % 2

array([1, 0, 1])

In [31]:
p > 8

array([ True, False, False])

In [32]:
p < 8

array([False, False,  True])

In [33]:
x = np.array(([2, 1],[1, 3]))
y = np.array(([3, 2],[4, 2]))

In [34]:
x + y

array([[5, 3],
       [5, 5]])

In [35]:
x - y

array([[-1, -1],
       [-3,  1]])

In [36]:
x * y

array([[6, 2],
       [4, 6]])

In [37]:
x.dot(y)

array([[10,  6],
       [15,  8]])

In [38]:
np.dot(x,y)

array([[10,  6],
       [15,  8]])

In [39]:
x *= 4
x

array([[ 8,  4],
       [ 4, 12]])

In [40]:
x.sum()

np.int64(28)

In [42]:
x.min()

np.int64(4)

In [43]:
x.mean()

np.float64(7.0)

In [45]:
num = np.arange(16).reshape(4,4)

In [46]:
num.sum()

np.int64(120)

In [50]:
num

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
num.sum(axis = 0)

array([24, 28, 32, 36])

In [49]:
num.sum(axis = 1)

array([ 6, 22, 38, 54])

In [51]:
num.mean(axis = 1)

array([ 1.5,  5.5,  9.5, 13.5])